import type { Metadata } from 'next';
import { roboto_flex } from '@/app/fonts';

import './globals.css';

import Navbar from '@/components/ui/navigation/desktop/Navbar';
import Providers from '@/app/providers';

export const metadata: Metadata = {
  title: 'R8TED Collections',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={roboto_flex.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
